window.CBC_PRODUCTS = {
  'tee-1': {
    name: 'Футболка California Boxing Club',
    breadcrumb: 'Футболка',
    category: 'Футболки',
    price: '5 990 ₽',
    lead: 'Оверсайз-футболка с вышитым логотипом клуба. Плотный хлопок, удобная посадка — для зала и города.',
    modelParams: 'параметры модели: рост 160, обхваты 84/58/92, размер на модели S.',
    print:       'нанесение: спереди вышивка фирменного логотипа.',
    color:       'цвет: White',
    care: 'Материал: 100% хлопок, кулирка 230 грамм',
    images: [
      'images/california7934.jpg',
      'images/california7935.jpg',
      'images/california7936.jpg',
      'images/california7937.jpg',
      'images/california7938.jpg',
    ],
  },
  'tee-2': {
    name: 'Футболка California Boxing Club',
    breadcrumb: 'Футболка',
    category: 'Футболки',
    price: '5 990 ₽',
    lead: 'Футболка от C.B.C - THIS IS BOXING AWESOME! ®️',
    modelParams: 'параметры модели: рост 180см, обхваты 107/85/100, размер на модели XL.',
    print:       'нанесение: спереди вышивка фирменного логотипа.',
    color:       'цвет: Black',
    care: 'материал: 100% хлопок, кулирка 230 грамм',
    images: [
      'images/california8007.jpg',
      'images/california8010.jpg',
      'images/california8011.jpg',
      'images/california8012.jpg',
      'images/california8013.jpg',
    ],
  },
  'tee-3': {
    name: 'Футболка California Boxing Club',
    breadcrumb: 'Футболка',
    category: 'Футболки',
    price: '4 490 ₽',
    lead: 'Футболка от C.B.C - THIS IS BOXING AWESOME! ®️',
    modelParams: 'параметры модели: рост 160, обхваты 84/58/92, размер на модели S.',
    print:       'нанесение: спереди фирменный логотип из ДТФ печати, на груди расположился флаг России внутри логотипа CALIFORNIA BOXING CLUB, сзади принт из ДТФ печати, на спине Штаты Америки и столица России - Москва',
    color:       'цвет: Black',
    care: 'материал: 100% хлопок, кулирка 180 грамм',
    images: [
      'images/california7891.jpg',
      'images/california7892.jpg',
      'images/california7893.jpg',
      'images/california7896.jpg',
      'images/california7898.jpg',
    ],
  },
  'tee-4': {
    name: 'Футболка California Boxing Club',
    breadcrumb: 'Футболка',
    category: 'Футболки',
    price: '4 490 ₽',
    lead: 'Футболка от C.B.C - THIS IS BOXING AWESOME! ®️',
    modelParams: 'параметры модели: рост 180см, обхваты 107/85/100, размер на модели XL.',
    print:       'нанесение: спереди фирменный логотип из ДТФ печати, на груди расположился флаг России внутри логотипа CALIFORNIA BOXING CLUB, сзади принт из ДТФ печати, на спине Штаты Америки и столица России - Москва',
    color:       'цвет: White',
    care: 'материал: 100% хлопок, кулирка 180 грамм.',
    images: [
      'images/california8050.jpg',
      'images/california8051.jpg',
      'images/california8055.jpg',
      'images/california8057.jpg',
      'images/california8060.jpg',
    ],
  },
  'tee-5': {
    name: 'Футболка California Boxing Club',
    breadcrumb: 'Футболка',
    category: 'Футболки',
    price: '6 990 ₽',
    lead: 'Футболка от C.B.C - THIS IS BOXING AWESOME! ®️',
    modelParams: 'параметры модели: рост 160, обхваты 84/58/92, размер на модели S.',
    print:       'нанесение: спереди фирменный логотип из ДТФ печати, сзади принт сделаный с помощью цветной печати. Картина в виде ринга CALIFORNIA BOXING CLUB написана художником от руки. Дополняет картину надпись - FOREVER ROUNDS WITH LIFE …u never know when’s the last one',
    color:       'цвет: White',
    care: 'материал: 100% хлопок, кулирка 230 грамм.',
    images: [
      'images/california7945.jpg',
      'images/california7946.jpg',
      'images/california7947.jpg',
      'images/california7948.jpg',
      'images/california7949.jpg',
    ],
  },
  'tee-6': {
    name: 'Футболка California Boxing Club',
    breadcrumb: 'Футболка',
    category: 'Футболки',
    price: '6 990 ₽',
    lead: 'Футболка от C.B.C - THIS IS BOXING AWESOME! ®️',
    modelParams: 'параметры модели: рост 180см, обхваты 107/85/100, размер на модели XL.',
    print:       'нанесение: спереди фирменный логотип из ДТФ печати, сзади принт сделаный с помощью цветной печати. Картина в виде ринга CALIFORNIA BOXING CLUB написана художником от руки. Дополняет картину надпись - FOREVER ROUNDS WITH LIFE …u never know when’s the last one',
    color:       'цвет: Black',
    care: 'материал: 100% хлопок, кулирка 230 грамм.',
    images: [
      'images/california8029.jpg',
      'images/california8031.jpg',
      'images/california8032.jpg',
      'images/california8034.jpg',
      'images/california8035.jpg',
    ],
  },
};
